/**
 * MUI Icons Re-export
 * Centralized icon exports using Material-UI icons
 */

import {
  Add,
  AttachFile,
  Bookmark,
  Brightness4,
  Brightness7,
  Call,
  CallEnd,
  Chat,
  Check,
  ChevronLeft,
  ChevronRight,
  Close,
  ContentCopy,
  DateRange,
  Delete,
  Download,
  Edit,
  Email,
  EmojiEmotions,
  Error,
  ExpandLess,
  ExpandMore,
  Favorite,
  FilterList,
  Fullscreen,
  FullscreenExit,
  Group,
  Home,
  Image,
  Info,
  KeyboardArrowDown,
  KeyboardArrowLeft,
  KeyboardArrowRight,
  KeyboardArrowUp,
  Language,
  Link,
  LinkOff,
  LocationOn,
  Menu,
  Mic,
  MicOff,
  MoreVert,
  Notifications,
  NotificationsOff,
  Pause,
  Person,
  Phone,
  PhotoCamera,
  PlayArrow,
  Refresh,
  ReportProblem,
  Schedule,
  Search,
  Send,
  Settings,
  Share,
  SmartToy,
  Sort,
  Star,
  Stop,
  Upload,
  VideoCall,
  ViewList,
  ViewModule,
  Visibility,
  VisibilityOff,
  VolumeOff,
  VolumeUp,
  Warning,
} from '@mui/icons-material';

// Re-export with custom names for backward compatibility
export {
  ReportProblem as AlertCircle, KeyboardArrowDown as ArrowDown,
  KeyboardArrowLeft as ArrowLeft,
  KeyboardArrowRight as ArrowRight, KeyboardArrowUp as ArrowUp, Bookmark, SmartToy as Bot, DateRange as Calendar, PhotoCamera as Camera, Check, ChevronLeft,
  ChevronRight, Schedule as Clock, ContentCopy as Copy, Download, Edit, Email, Error, ExpandLess, ExpandMore, Visibility as Eye,
  VisibilityOff as EyeOff, FilterList as Filter, ViewModule as Grid, Favorite as Heart, Home, Image, Info, Language, Link,
  LinkOff, ViewList as List, LocationOn as MapPin, Fullscreen as Maximize, Menu, Chat as MessageCircle, Mic,
  MicOff, FullscreenExit as Minimize, Brightness4 as Moon, MoreVert as MoreVertical, Notifications,
  NotificationsOff, AttachFile as Paperclip, Pause, Call as Phone, PlayArrow as Play, Add as Plus, Refresh, Search, Send, Settings, Share, Sort, Star as Sparkles, Stop, Brightness7 as Sun, Delete as Trash, Upload, Person as User,
  Group as Users, VideoCall as Video, VolumeOff, VolumeUp, Warning, Close as X
};

// Legacy compatibility - Icons object for existing code that might use this pattern
export const Icons = {
  Phone: Phone,
  PhoneOff: CallEnd,
  Search: Search,
  Settings: Settings,
  Send: Send,
  MoreVertical: MoreVert,
  VolumeOff: VolumeOff,
  VolumeUp: VolumeUp,
  Warning: Warning,
  Video: VideoCall,
  Users: Group,
  User: Person,
  Bot: SmartToy,
  X: Close,
  Paperclip: AttachFile,
  ChevronDown: ExpandMore,
  Menu: Menu,
  Smile: EmojiEmotions,
  MessageCircle: Chat,
  Plus: Add,
  Trash: Delete,
  Check: Check,
  Copy: ContentCopy
};

